#!/bin/sh

FILE1=/tmp/Assignment_timezone-$$
FILE2=/tmp/Assignment_timezone-$$
FILE3=/tmp/Assignment_timezone-$$

DIALOG=${DIALOG=dialog}

$DIALOG --title " Timezone" --clear \
       \
        --inputbox "put continent/country name: " 25 59 4>/tmp/input.$$

now1=$(export TZ=`cat /tmp/input.$$`;date)


MSG="Time is:  $now1 \n\nContinue?"
		$DIALOG --yesno "$MSG" 25 59 || end


